version: '3.7'

services:

  database:
    image: postgres
    container_name: casa-maria-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cpf_blacklist
    volumes:
      - pgdata:/data/postgres

  # app:
    # build: .
    # container_name: casa-maria
    # ports:
    #   - 3080:3080
    # volumes:
    #   - .:/usr/apps
    # links: 
    #   - database
    # depends_on:
    #   - database


volumes:
  pgdata:
    driver: local